# Generated by Django 5.1.3 on 2024-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_simpson_team_remove_simpson_type_simpson_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpson',
            name='surnom',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
